dist: trusty
language: python
python:
  - "3.6"

env:
  - SPHINX_SPEC=Sphinx~=1.2.0
  - SPHINX_SPEC=git+https://github.com/sphinx-doc/sphinx.git#egg=Sphinx-dev

install:
  - pip install $SPHINX_SPEC
  - python setup.py install

before_script:
  - git config --global user.email "jared.dillard+travis@gmail.com"
  - git config --global user.name "Travis Build"